name: platform-input-support-py2.7
channels:
  - conda-forge
  - defaults
dependencies:
  - addict=2.2.0
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=18.2.0
  - blas=1.1=openblas
  - ca-certificates=2018.11.29=ha4d7672_0
  - cachetools=2.1.0
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - configargparse=0.13.0
  - coverage=4.5.2
  - enum34=1.1.6
  - funcsigs=1.0.2
  - futures=3.2.0
  - google-api-core=1.7.0
  - google-auth=1.6.2
  - google-auth-httplib2=0.0.3
  - google-cloud-core=0.24.1
  - google-cloud-storage=1.1.1
  - google-resumable-media=0.0.2
  - googleapis-common-protos=1.5.6
  - httplib2=0.12.0
  - idna=2.8
  - ipaddress=1.0.22
  - libprotobuf=3.6.1
  - mock=2.0.0
  - more-itertools=4.3.0
  - numpy=1.16.1
  - openblas=0.3.3
  - openssl=1.1.1a
  - pathlib2=2.3.3
  - pbr=5.1.2
  - pluggy=0.8.1
  - protobuf=3.6.1
  - py=1.7.0
  - pyaml=18.11.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.6.8
  - pytest=4.2.0
  - pytest-cov=2.6.1
  - pytz=2018.9
  - pyyaml=3.13
  - requests=2.21.0
  - rsa=3.4.2
  - scandir=1.9.0
  - six=1.12.0
  - toolz=0.9.0
  - tqdm=4.31.1
  - urllib3=1.24.1
  - yaml=0.1.7
  - cryptography=2.5
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - pip=19.0.1
  - python=2.7.15
  - readline=7.0
  - requests-file=1.4.3
  - setuptools=40.7.3
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - zlib=1.2.11


