name: otpis
channels:
  - conda-forge
  - defaults
dependencies:
 - addict
 - configargparse
 - elasticsearch
 - elasticsearch-dsl
 - jsonlines
 - google-cloud-storage=1.42.3
 - mock
 - pip
 - python=3.8.8
 - pytest
 - pytest-cov
 - pyyaml
 - yapsy
 - tqdm
 - pip:
   - future==0.18.2
   - opentargets-urlzsource==1.0.0
   - requests-file==1.5.1
